set(VCPKG_CMAKE_SYSTEM_NAME)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CRT_LINKAGE static)

set(VCPKG_C_FLAGS_RELEASE "/Gy /GL /Gw")
set(VCPKG_CXX_FLAGS_RELEASE "/Gy /GL /Gw")
set(VCPKG_LINKER_FLAGS_RELEASE "/OPT:ICF=3 /LTCG")
