name: Build and Upload (on release)

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Switch
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build
        env:
          CIBW_SKIP: "pp*"
          CIBW_BUILD: "*win_amd64 *mac*"
          CIBW_BUILD_FRONTEND: build
          MACOSX_DEPLOYMENT_TARGET: "13.3"
        uses: pypa/cibuildwheel@v2.18.1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_linux:
    name: Build wheels on linux
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S python ninja cmake git curl zip unzip tar
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install pipx

      - name: Build
        run: |
          source .venv/bin/activate
          pipx run build
          platform="$(ldd --version | awk '/ldd/{gsub(/\./, "_", $NF); print "manylinux_" $NF "_x86_64"}')"
          pipx run wheel tags --remove --platform=${platform} dist/*linux_x86_64.whl

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheel-linux
          path: dist/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: pipx run build --sdist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  upload:
    name: Upload to PyPI
    needs: [build_wheels, build_linux, build_sdist]
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
