name: Build and Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Setup Developer Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          python -m venv .venv
          .venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install . -v `
            -C override=cmake.args+=["--toolchain=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"]

      - name: Test
        run: |
          .venv\Scripts\Activate.ps1
          pip install --group test
          pytest test

  build_macos:
    name: Build and Test on MacOS
    runs-on: macos-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Switch
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
          MACOSX_DEPLOYMENT_TARGET: 13.3
          ARCHFLAGS: "-arch arm64"
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install . -v \
            -C override=cmake.options.VELOCEM_BOOTSTRAP_VCPKG="ON" \
            -C override=cmake.options.VCPKG_OSX_DEPLOYMENT_TARGET=\"13.3\"

      - name: Test
        run: |
          . .venv/bin/activate
          pip install --group test
          pytest test

  build_linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install . -v \
            -C override=cmake.args+=\["--toolchain=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"\]

      - name: Test
        run: |
          . .venv/bin/activate
          pip install --group test
          pytest test
